### ISSUE TITLE
how to add new transection or  what about admin stuff

### ISSUE THREAD

**Issue by manojgoje** [DharshiBalasubramaniyam/Fullstack-Expense-Tracker#1]
i have clone this repository and did imp changes like database and setup mail also i have login as a user but i unable to post any new transection why please solve this problm 
 &
what about admin ? 

how admin is logged in ?
where is admin login page ?

please mam give information regarding this

**Comment by DharshiBalasubramaniyam** [comment]
Both admin and user use same page for login.
You can to store admin details in dB manually and then login using same credentials.

And regarding couldn't add transaction, can you able to register successfully using otp?

**Comment by manojgoje** [comment]
yes ,
i have succesfully logged in into webapp but there is o option of adding transection
i will send the SS 




<img width="960" alt="no option of add transection" src="https://github.com/user-attachments/assets/0e15b88b-7e03-45ad-accc-e1a0c202c8da">
<img width="960" alt="not have any log regarding this problem" src="https://github.com/user-attachments/assets/730936ed-aa81-4710-983f-72369909ef41">

**Comment by DharshiBalasubramaniyam** [comment]
> yes , i have succesfully logged in into webapp but there is o option of adding transection i will send the SS
> 
> and which table we have to add admin details .........?
> 
> <img alt="db" width="960" src="https://private-user-images.githubusercontent.com/129887840/369364399-3a8c2b71-77cf-4a19-9aa6-dbb66f4c99a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4Mjg4MDcsIm5iZiI6MTcyNjgyODUwNywicGF0aCI6Ii8xMjk4ODc4NDAvMzY5MzY0Mzk5LTNhOGMyYjcxLTc3Y2YtNGExOS05YWE2LWRiYjY2ZjRjOTlhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxMDM1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjhkZjExYjI5MzFmZDMwNDFkODI1YzYxYTI3NjI4OGRiMzE3M2UwMDU0MGI1OTJlZTg1NGQwMGY5ZjkzZjBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.q2ohKpsUliSLjfpphN-JEKzB7r71C21LUB_zvFwM19c"> <img alt="no option of add transection" width="960" src="https://private-user-images.githubusercontent.com/129887840/369361887-0e15b88b-7e03-45ad-accc-e1a0c202c8da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4Mjg4MDcsIm5iZiI6MTcyNjgyODUwNywicGF0aCI6Ii8xMjk4ODc4NDAvMzY5MzYxODg3LTBlMTViODhiLTdlMDMtNDVhZC1hY2NjLWUxYTBjMjAyYzhkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxMDM1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjZkZjRhOGI0YzBkMmM5YTc4NDhmMDg2MWVmZWI0MTgxM2UxM2UzY2IxYWMyZmZkMzAyOGE4OTUwNjE0YTkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3Om0zS42aIsIFg40DPTtNE-6GKpoo8YUPpv0CemLE7Q"> <img alt="not have any log regarding this problem" width="960" src="https://private-user-images.githubusercontent.com/129887840/369361910-730936ed-aa81-4710-983f-72369909ef41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4Mjg4MDcsIm5iZiI6MTcyNjgyODUwNywicGF0aCI6Ii8xMjk4ODc4NDAvMzY5MzYxOTEwLTczMDkzNmVkLWFhODEtNDcxMC05ODNmLTcyMzY5OTA5ZWY0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxMDM1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWU1YjljZTlhNDQ5Y2U3N2U4NzU0ZGEwY2RkMmEyNjcwZGQxODRiYjU1MGU4MjUxMDgxMjM0MmVjM2QzZjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BM-Mza7YbZ79H0wb4HkQ-hhYgXZ_CRusft9xlUHB3Ow">

In users table, give reference  to admin role for role id.

You have to store some categories for both expense and income in category table. Without categories you can't add transaction. Once you stored categories ( like salary, food, health etc.) refresh the page and see whether it's ok or not.

**Comment by manojgoje** [comment]
problem was solved 
thank you so much for the support ❤
